name: Deploy Infrastructure

on:
  push:
    branches: [ main, develop, observabilityBranch ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: us-east-1
  TF_VERSION: '1.12.2'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Init
      run: terraform init -backend-config=backend.conf

    - name: Force Unlock Any Stuck Locks
      run: |
        echo "Checking for stuck locks..."
        # Try to get lock info and extract lock ID
        LOCK_OUTPUT=$(terraform plan -var="account_name=marc10010" 2>&1 || true)
        if echo "$LOCK_OUTPUT" | grep -q "Lock Info:"; then
          LOCK_ID=$(echo "$LOCK_OUTPUT" | grep -A 10 "Lock Info:" | grep "ID:" | sed 's/.*ID:[[:space:]]*//' | tr -d ' ')
          if [ -n "$LOCK_ID" ]; then
            echo "Found stuck lock with ID: $LOCK_ID"
            echo "Attempting to force unlock..."
            terraform force-unlock -force "$LOCK_ID" || echo "Failed to unlock $LOCK_ID"
          fi
        else
          echo "No stuck locks found"
        fi
      continue-on-error: true

    - name: Terraform Plan
      run: terraform plan -var="account_name=marc10010" -lock-timeout=2m
      continue-on-error: true

    - name: Terraform Apply Infrastructure
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/observabilityBranch'
      run: terraform apply -auto-approve -var="account_name=marc10010"

    - name: Output Success
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/observabilityBranch'
      run: |
        echo "🎉 Despliegue completado!"
        echo "API Gateway URL: $(terraform output -raw api_gateway_url)"
