name: Destroy Infrastructure

on:
  workflow_dispatch:  # Solo se ejecuta manualmente
  push:
    branches: [ destroy ]  # O en una rama específica

env:
  AWS_REGION: us-east-1
  TF_VERSION: '1.12.2'

jobs:
  destroy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Init
      run: terraform init -backend-config=backend.conf

    - name: Terraform Destroy
      run: terraform destroy -auto-approve -backend-config=backend.conf

    - name: Output
      run: |
        echo "🗑️  Infraestructura destruida completamente!"
